export enum UserTypeEnum {
  STUDENT = "STUDENT",
  AGENT = "AGENT",
  ADMIN = "ADMIN",
  PENDING_AGENT = "PENDING_AGENT",
  SELECTED_AGENT = "SELECTED_AGENT",
  PARTIAL_REGISTER_STUDENT = "PARTIAL_REGISTER_STUDENT",
  PARTIAL_REGISTER_AGENT = "PARTIAL_REGISTER_AGENT",
}

export enum AuthTabEnum {
  LOGIN = "login",
  REGISTER = "register"
}
